#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../Utils/hash.h"

#define MAX_LINE 256

static void trim(char *s) {
    size_t len = strlen(s);
    if (len > 0 && s[len - 1] == '\n')
        s[len - 1] = '\0';
}

static void to_macro(const char *input, char *out) {
    sprintf(out, "M_HASH_%s", input);

    for (int i = 0; out[i]; i++) {
        if (out[i] >= 'a' && out[i] <= 'z')
            out[i] = out[i] - 'a' + 'A';
    }
}

int main() {
    char line[MAX_LINE];

    printf("#ifndef MONKEYKERNELSYNTAX_METHODS_CACHE_H\n");
    printf("#define MONKEYKERNELSYNTAX_METHODS_CACHE_H\n\n");

    printf("// AUTO-GENERATED FILE\n");
    printf("// Generated by gen_hashes\n\n");

    while (fgets(line, sizeof(line), stdin)) {
        trim(line);

        if (strlen(line) == 0)
            continue;

        unsigned int hash = get_hash(line);

        char macro[512];
        to_macro(line, macro);

        printf("#define %s 0x%x  // \"%s\"\n", macro, hash, line);
    }

    printf("\n#endif // MONKEYKERNELSYNTAX_METHODS_CACHE_H\n");

    return 0;
}