name: MKS Auto-Release

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            c_compiler: cl
            exe_name: mks_run.exe
            out_name: mks_run-windows-amd64.exe
            path: build/Release
          - os: ubuntu-latest
            c_compiler: gcc
            exe_name: mks_run
            out_name: mks_run-linux-amd64
            path: build
            
    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Prepare Binaries
      shell: bash
      run: |
        mkdir dist
        cp ${{ matrix.path }}/${{ matrix.exe_name }} dist/${{ matrix.out_name }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-${{ matrix.os }}
        path: dist/*


  release:
    needs: build 
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: artifacts-*
        path: release_files
        merge-multiple: true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "latest"
        name: "🔥 MKS Latest Build"
        files: release_files/*
